import { readdirSync, rmSync } from "node:fs";
import { resolve } from "node:path";

// Safe-to-delete local outputs. These are generated by tooling and can be recreated.
const fixedTargets = [
  ".zerog-memory",
  "cache",
  "reconciliation-logs",
  "artifacts",
  "coverage",
  "dist",
  "typechain-types",
  "indexer/index-state.json",
];

for (const target of fixedTargets) {
  const absoluteTarget = resolve(process.cwd(), target);
  rmSync(absoluteTarget, { recursive: true, force: true });
  console.log(`removed: ${target}`);
}

// Remove TypeScript incremental build cache files in repo root.
for (const entry of readdirSync(process.cwd(), { withFileTypes: true })) {
  if (entry.isFile() && entry.name.endsWith(".tsbuildinfo")) {
    rmSync(resolve(process.cwd(), entry.name), { force: true });
    console.log(`removed: ${entry.name}`);
  }
}

console.log("all local generated artifacts cleaned");
